src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('', include('inventory.urls')),
    path('', include('users.urls')),
    path('', include('dealer.urls')),
    path('', include('customer.urls')),
    path('', include('tool.urls')),
    path('', include('lubricant.urls')),
    path('', include('dashboard.urls')),
    path('', include('harvester.urls')),
    path('summernote/', include('django_summernote.urls')),
    # path('oauth/', include('social_django.urls', namespace='social')),
    # path('', TemplateView.as_view(template_name="signup.html")),
    # path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from dashboard.models import State, District, Municipality


class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class User(AbstractUser):

    is_customer = models.BooleanField(default=False)
    is_dealer = models.BooleanField(default=False)
    email = models.EmailField(max_length=254, unique=True)

    class Meta:
        verbose_name = _("User")
        verbose_name_plural = _("Users")

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("User_detail", kwargs={"pk": self.pk})


class UserProfile(models.Model):

    address = models.CharField(_("Address"), max_length=50)
    contact = models.CharField(_("Phone Number"), max_length=50)
    user = models.OneToOneField(User, verbose_name=_(
        "User"), on_delete=models.CASCADE, null=True,)

    class Meta:
        verbose_name = _("Profile")
        verbose_name_plural = _("Profiles")

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse("Profile_detail", kwargs={"pk": self.pk})


class SellerDetail(models.Model):

    name = models.CharField(_("Name"), max_length=500)
    phone_no = models.CharField(_("Phone Number"), max_length=50)
    email = models.EmailField(null=True, blank=True)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    address = models.CharField(_("Full Address"), max_length=500)
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    pincode = models.CharField(max_length=250, null=True, blank=True)
    municipality = models.ForeignKey(
        Municipality, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        verbose_name = _("SellerDetail")
        verbose_name_plural = _("SellerDetails")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("SellerDetail_detail", kwargs={"pk": self.pk})


class AdminUser(User):
    full_name = models.CharField(max_length=250)
    image = models.ImageField(upload_to='admin')
    address = models.CharField(max_length=250)
    contact = models.CharField(max_length=250)

    def __str__(self):
        return self.first_name

templates/layout/admin/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token }}">

    <title>{% block title %}{% endblock %} | Admin Dashboard</title>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'admin/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/adminlte.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/admin.css' %}"> {% block static %}{% endblock %}
    <link rel="icon" href="{% static 'images/icons/favicon.ico' %}" type="image/icon" sizes="16x16">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
    <link
      href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"
      rel="stylesheet"
    />
    {% block style %}

    {% endblock %}
    <style> 
        .form-error{
          color : red;
          padding: 0;
        }
  
        .form-error ul li{
          list-style:none;
          padding: 0;
        }
  
        .form-inline{
            display: flex;
            flex-flow: row wrap;
            align-items: center;
        }   
  
        .form-inline input{
              margin: 5px 5px 5px 0;
        } 
  
        span .switch-btn{
          margin: 0px 10px 0 10px;
        }
        </style>

</head>

<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        {% include 'layout/admin/header.html' %}
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            {% block content %} {% endblock %}
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        {% include 'layout/admin/footer.html' %}
    </div>
    <!-- ./wrapper -->

    <!-- REQUIRED SCRIPTS -->

    <!-- jQuery -->
    <script src="/static/js/jquery-3.5.1.min.js"></script>
    <script src="{% static 'admin/js/popper.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'admin/js/bootstrap.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'admin/js/adminlte.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
        <!-- select2-->
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
      $("#id_state").change(function () {
        var url = $("#addressForm").attr("data-district-url");  // get the url of the `load_cities` view
        var provinceId = $(this).val();  // get the selected country ID from the HTML input
    
        $.ajax({                       // initialize an AJAX request
          url: url, 
          method:'GET',                   // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
          data: {
            'state': provinceId       // add the country id to the GET parameters
          },
          success: function (data) {   // `data` is the return of the `load_cities` view function
            $("#id_district").html(data);  // replace the contents of the city input with the data that came from the server
          }
        });
    
      });
      $("#id_district").change(function () {
        var url = $("#addressForm").attr("data-municipality-url");  // get the url of the `load_cities` view
        var districtId = $(this).val();  // get the selected country ID from the HTML input
    
        $.ajax({                       // initialize an AJAX request
          url: url, 
          method:'GET',                   // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
          data: {
            'district': districtId       // add the country id to the GET parameters
          },
          success: function (data) {   // `data` is the return of the `load_cities` view function
            $("#id_municipality").html(data);  // replace the contents of the city input with the data that came from the server
          }
        });
    
      });
    </script>
    <script>
      $(".select2").select2({ 
            width: '100%',
        });

    </script>
    {% block script%}{% endblock %}
</body>

</html>

templates/layout/admin/footer.html
{% load static %}
<footer class="main-footer">
    <!-- Default to the left -->
    <strong>Copyright &copy; 2021 <a href="">Tractor</a>.</strong> All rights reserved.
</footer>

templates/layout/admin/header1.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand bg-white navbar-light border-bottom">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
        </li>
    </ul>
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fa fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fa fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fa fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-user"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <a href="#" class="dropdown-item">
                Logout
            </a>
            </div>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="" class="brand-link">
        <img src="{% static 'images/logo/logo-white.png' %}" alt="Tractor" class="brand-image img-circle elevation-3">
        <span class="brand-text font-weight-bold">Tractor Shop</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon t-nav-icon fas fa-warehouse"></i>
                        <p>
                            Inventory
                            <i class="right fa fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'brand-table' %}" class="nav-link">
                                <i class="nav-icon t-nav-icon fas fa-clipboard"></i>
                                <p>Brands</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="fas fa-link nav-icon t-nav-icon"></i>
                                <p>Categorys</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="fas fa-weight-hanging nav-icon t-nav-icon"></i>
                                <p>Dimension And Weights</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="fab fa-searchengin nav-icon t-nav-icon"></i>
                                <p>Engines</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="fas fa-sort-amount-up nav-icon t-nav-icon"></i>
                                <p>Hydraulices</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="fas fa-images nav-icon t-nav-icon"></i>
                                <p>Images</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="fas fa-tractor nav-icon t-nav-icon"></i>
                                <p>Old Tractors</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="fas fa-info-circle nav-icon t-nav-icon"></i>
                                <p>Other Informations</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="fas fa-bolt nav-icon t-nav-icon"></i>
                                <p>Powers</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="far fa-circle nav-icon t-nav-icon"></i>
                                <p>Steering</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="fas fa-tractor nav-icon t-nav-icon"></i>
                                <p>Tractors</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="fas fa-dolly-flatbed nav-icon t-nav-icon"></i>
                                <p>Transmissions</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="fas fa-dharmachakra nav-icon t-nav-icon"></i>
                                <p>Wheel And Tyres</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon t-nav-icon fas fa-user-circle"></i>
                        <p>
                            Users
                            <i class="right fa fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon t-nav-icon fas fa-user"></i>
                                <p>Profiles</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'seller-detail' %}" class="nav-link">
                                <i class="fas fa-id-card nav-icon t-nav-icon"></i>
                                <p>Seller Details</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="fas fa-users nav-icon t-nav-icon"></i>
                                <p>User</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon t-nav-icon far fa-user-circle"></i>
                        <p>
                            Customer
                            <i class="right fa fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'question' %}" class="nav-link">
                                <i class="nav-icon t-nav-icon fas fa-question-circle"></i>
                                <p>Questions</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'answer' %}" class="nav-link">
                                <i class="nav-icon t-nav-icon fas fa-arrow-circle-right"></i>
                                <p>Answers</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'apply-insurance' %}" class="nav-link">
                                <i class="fas fa-file-contract nav-icon t-nav-icon"></i>
                                <p>Apply Insurances</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'apply-loan' %}" class="nav-link">
                                <i class="fas fa-file-signature nav-icon t-nav-icon"></i>
                                <p>Apply Loan</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="{% url 'dealership-enquiry' %}" class="nav-link">
                        <i class="t-nav-icon nav-icon fas fa-clipboard"></i>
                        <p>
                            Dealership Enquirys
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'news-category' %}" class="nav-link">
                        <i class="t-nav-icon nav-icon far fa-newspaper"></i>
                        <p>
                            News Categorys
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'news-dashboard' %}" class="nav-link">
                        <i class="t-nav-icon nav-icon fas fa-newspaper"></i>
                        <p>
                            News
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'post-category' %}" class="nav-link">
                        <i class="t-nav-icon nav-icon fas fa-blog"></i>
                        <p>
                            Posts Categorys
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'post' %}" class="nav-link">
                        <i class="t-nav-icon nav-icon fab fa-blogger-b"></i>
                        <p>
                            Posts
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>